import { Paper, Question } from '../types';

// Helper function to get actual question count for a paper
export const getQuestionCount = (paperId: string): number => {
  return MOCK_QUESTIONS[paperId]?.length || 0;
};

export const MOCK_QUESTIONS: { [paperId: string]: Question[] } = {
  // Paper 1: TEF Compréhension Orale - Niveau A1 (Beginner)
  '1': [
    {
      id: 'q1_1',
      question: 'Quelle est la capitale de la France?',
      options: ['Paris', 'Lyon', 'Marseille', 'Bordeaux'],
      correctAnswer: 0,
      explanation: 'Paris est la capitale et la plus grande ville de France.',
    },
    {
      id: 'q1_2',
      question: 'Comment dit-on "Hello" en français?',
      options: ['Au revoir', 'Bonjour', 'Merci', 'Oui'],
      correctAnswer: 1,
      explanation: '"Bonjour" signifie "Hello" ou "Good morning" en français.',
    },
    {
      id: 'q1_3',
      question: 'Quel est le verbe "être" à la première personne du singulier?',
      options: ['Je suis', 'Tu es', 'Il est', 'Nous sommes'],
      correctAnswer: 0,
      explanation: '"Je suis" est la conjugaison de "être" pour "I am".',
    },
    {
      id: 'q1_4',
      question: 'Comment dit-on "Thank you" en français?',
      options: ['S\'il vous plaît', 'Merci', 'Pardon', 'Excusez-moi'],
      correctAnswer: 1,
      explanation: '"Merci" signifie "Thank you" en français.',
    },
    {
      id: 'q1_5',
      question: 'Quel mot signifie "water"?',
      options: ['Pain', 'Eau', 'Lait', 'Café'],
      correctAnswer: 1,
      explanation: '"Eau" signifie "water" en français.',
    },
    {
      id: 'q1_6',
      question: 'Comment demander "How are you?"',
      options: ['Au revoir', 'Bonne nuit', 'Comment allez-vous?', 'À bientôt'],
      correctAnswer: 2,
      explanation: '"Comment allez-vous?" est la façon formelle de demander "How are you?"',
    },
    {
      id: 'q1_7',
      question: 'Quel nombre est "dix"?',
      options: ['5', '10', '15', '20'],
      correctAnswer: 1,
      explanation: '"Dix" signifie "ten" (10) en français.',
    },
    {
      id: 'q1_8',
      question: 'Quel jour vient après lundi?',
      options: ['Dimanche', 'Mercredi', 'Mardi', 'Jeudi'],
      correctAnswer: 2,
      explanation: 'Mardi vient après lundi dans la semaine.',
    },
    {
      id: 'q1_9',
      question: 'Comment dit-on "Yes" en français?',
      options: ['Non', 'Oui', 'Peut-être', 'Jamais'],
      correctAnswer: 1,
      explanation: '"Oui" signifie "Yes" en français.',
    },
    {
      id: 'q1_10',
      question: 'Quel mot signifie "house"?',
      options: ['Voiture', 'Maison', 'École', 'Magasin'],
      correctAnswer: 1,
      explanation: '"Maison" signifie "house" en français.',
    },
  ],

  // Paper 7: TEF Compréhension Orale - Niveau A2 (Beginner)
  '7': [
    {
      id: 'q7_1',
      question: 'Où peut-on acheter du pain?',
      options: ['À la boucherie', 'À la boulangerie', 'À la pharmacie', 'À la poste'],
      correctAnswer: 1,
      explanation: 'On achète du pain à la boulangerie.',
    },
    {
      id: 'q7_2',
      question: 'Quel temps fait-il quand il pleut?',
      options: ['Il fait beau', 'Il fait mauvais', 'Il fait chaud', 'Il fait froid uniquement'],
      correctAnswer: 1,
      explanation: 'Quand il pleut, on dit qu\'il fait mauvais.',
    },
    {
      id: 'q7_3',
      question: 'À quelle heure commence généralement le travail?',
      options: ['À minuit', 'Le matin', 'À midi', 'La nuit'],
      correctAnswer: 1,
      explanation: 'Le travail commence généralement le matin.',
    },
    {
      id: 'q7_4',
      question: 'Que fait-on dans un restaurant?',
      options: ['On dort', 'On mange', 'On étudie', 'On nage'],
      correctAnswer: 1,
      explanation: 'Dans un restaurant, on mange.',
    },
    {
      id: 'q7_5',
      question: 'Quel transport utilise des rails?',
      options: ['Le bus', 'La voiture', 'Le train', 'L\'avion'],
      correctAnswer: 2,
      explanation: 'Le train utilise des rails pour se déplacer.',
    },
    {
      id: 'q7_6',
      question: 'Où va-t-on pour voir un médecin?',
      options: ['À l\'hôpital', 'Au cinéma', 'Au supermarché', 'À la bibliothèque'],
      correctAnswer: 0,
      explanation: 'On va à l\'hôpital ou chez le médecin pour voir un médecin.',
    },
    {
      id: 'q7_7',
      question: 'Quel repas prend-on le soir?',
      options: ['Le petit-déjeuner', 'Le déjeuner', 'Le dîner', 'Le goûter'],
      correctAnswer: 2,
      explanation: 'Le dîner est le repas du soir.',
    },
    {
      id: 'q7_8',
      question: 'Combien de saisons y a-t-il dans une année?',
      options: ['2', '3', '4', '5'],
      correctAnswer: 2,
      explanation: 'Il y a quatre saisons: printemps, été, automne et hiver.',
    },
    {
      id: 'q7_9',
      question: 'Que porte-t-on quand il fait froid?',
      options: ['Un maillot de bain', 'Un manteau', 'Des sandales', 'Des shorts'],
      correctAnswer: 1,
      explanation: 'On porte un manteau quand il fait froid.',
    },
    {
      id: 'q7_10',
      question: 'Où trouve-t-on des livres?',
      options: ['À la boulangerie', 'À la bibliothèque', 'À la piscine', 'Au garage'],
      correctAnswer: 1,
      explanation: 'On trouve des livres à la bibliothèque.',
    },
    {
      id: 'q7_11',
      question: 'Quelle couleur est le ciel par beau temps?',
      options: ['Rouge', 'Vert', 'Bleu', 'Noir'],
      correctAnswer: 2,
      explanation: 'Le ciel est bleu par beau temps.',
    },
    {
      id: 'q7_12',
      question: 'Quel animal dit "miaou"?',
      options: ['Le chien', 'Le chat', 'L\'oiseau', 'La vache'],
      correctAnswer: 1,
      explanation: 'Le chat fait "miaou".',
    },
  ],

  // Paper 8: TEF Compréhension Orale - Niveau B1 (Intermediate)
  '8': [
    {
      id: 'q8_1',
      question: 'Dans un dialogue, quelqu\'un dit: "Je suis désolé du retard". Que veut-il dire?',
      options: ['Il est en avance', 'Il s\'excuse d\'être en retard', 'Il part tôt', 'Il annule le rendez-vous'],
      correctAnswer: 1,
      explanation: '"Je suis désolé du retard" est une excuse pour être arrivé en retard.',
    },
    {
      id: 'q8_2',
      question: 'Que signifie l\'expression "avoir le cafard"?',
      options: ['Être content', 'Être triste', 'Avoir faim', 'Avoir peur'],
      correctAnswer: 1,
      explanation: '"Avoir le cafard" signifie être triste ou déprimé.',
    },
    {
      id: 'q8_3',
      question: 'Si quelqu\'un dit "Il fait un temps de chien", que signifie-t-il?',
      options: ['Il fait beau', 'Il fait très mauvais', 'Il aime les chiens', 'Il promène son chien'],
      correctAnswer: 1,
      explanation: '"Un temps de chien" signifie un très mauvais temps.',
    },
    {
      id: 'q8_4',
      question: 'Dans un magasin, on vous demande: "Vous désirez?" Que veut le vendeur?',
      options: ['Votre nom', 'Savoir ce que vous voulez acheter', 'Votre adresse', 'Votre opinion'],
      correctAnswer: 1,
      explanation: '"Vous désirez?" est une façon polie de demander ce que le client veut.',
    },
    {
      id: 'q8_5',
      question: 'Quelqu\'un dit: "Je m\'en occupe". Que va-t-il faire?',
      options: ['Ignorer le problème', 'Prendre en charge la situation', 'Partir', 'Attendre'],
      correctAnswer: 1,
      explanation: '"Je m\'en occupe" signifie "je vais gérer ça".',
    },
    {
      id: 'q8_6',
      question: 'Que veut dire "au bout du compte"?',
      options: ['Au début', 'Finalement', 'Rapidement', 'Jamais'],
      correctAnswer: 1,
      explanation: '"Au bout du compte" signifie "finalement" ou "en fin de compte".',
    },
    {
      id: 'q8_7',
      question: 'Si on dit "C\'est la goutte d\'eau qui fait déborder le vase", cela signifie:',
      options: ['Il y a trop d\'eau', 'C\'est le dernier problème qui rend la situation intolérable', 'Il faut boire', 'Il pleut'],
      correctAnswer: 1,
      explanation: 'Cette expression signifie que c\'est le dernier élément qui rend une situation insupportable.',
    },
    {
      id: 'q8_8',
      question: 'Dans une conversation professionnelle, "faire le point" signifie:',
      options: ['Dessiner', 'Faire une pause', 'Faire un bilan de la situation', 'Terminer'],
      correctAnswer: 2,
      explanation: '"Faire le point" signifie analyser où on en est dans un projet.',
    },
    {
      id: 'q8_9',
      question: 'Que signifie "mettre les pieds dans le plat"?',
      options: ['Cuisiner', 'Aborder un sujet délicat sans précaution', 'Danser', 'Se salir'],
      correctAnswer: 1,
      explanation: '"Mettre les pieds dans le plat" signifie parler d\'un sujet gênant sans diplomatie.',
    },
    {
      id: 'q8_10',
      question: 'Si quelqu\'un dit "J\'en ai marre", il exprime:',
      options: ['Sa joie', 'Son ennui ou sa frustration', 'Sa curiosité', 'Son étonnement'],
      correctAnswer: 1,
      explanation: '"J\'en ai marre" exprime l\'agacement ou la lassitude.',
    },
    {
      id: 'q8_11',
      question: 'Que veut dire "tourner autour du pot"?',
      options: ['Parler directement', 'Éviter d\'aborder le sujet principal', 'Cuisiner', 'Se perdre'],
      correctAnswer: 1,
      explanation: '"Tourner autour du pot" signifie ne pas aller droit au but.',
    },
    {
      id: 'q8_12',
      question: 'Dans un contexte professionnel, "rendre compte" signifie:',
      options: ['Payer', 'Faire un rapport', 'Comprendre', 'Compter'],
      correctAnswer: 1,
      explanation: '"Rendre compte" signifie faire un rapport ou informer quelqu\'un.',
    },
  ],

  // Paper 2: Expression Écrite - Niveau B1 (Intermediate)
  '2': [
    {
      id: 'q2_1',
      question: 'Quel temps verbal est utilisé pour parler d\'une action passée?',
      options: ['Présent', 'Futur', 'Passé composé', 'Conditionnel'],
      correctAnswer: 2,
      explanation: 'Le passé composé est utilisé pour décrire des actions terminées dans le passé.',
    },
    {
      id: 'q2_2',
      question: 'Quelle est la bonne formule pour commencer une lettre formelle?',
      options: ['Salut', 'Cher ami', 'Madame, Monsieur', 'Coucou'],
      correctAnswer: 2,
      explanation: '"Madame, Monsieur" est la formule de politesse standard pour une lettre formelle.',
    },
    {
      id: 'q2_3',
      question: 'Comment terminer une lettre de motivation?',
      options: ['À plus', 'Bisous', 'Cordialement', 'Salut'],
      correctAnswer: 2,
      explanation: '"Cordialement" ou "Je vous prie d\'agréer..." sont appropriés pour une lettre de motivation.',
    },
    {
      id: 'q2_4',
      question: 'Quel mot de liaison exprime la cause?',
      options: ['Donc', 'Mais', 'Car', 'Puis'],
      correctAnswer: 2,
      explanation: '"Car" exprime la cause, comme "parce que".',
    },
    {
      id: 'q2_5',
      question: 'Dans un email professionnel, comment demander poliment quelque chose?',
      options: ['Donne-moi', 'Je voudrais', 'Pourriez-vous', 'Tu peux'],
      correctAnswer: 2,
      explanation: '"Pourriez-vous" est la forme la plus polie pour faire une demande.',
    },
    {
      id: 'q2_6',
      question: 'Quel temps utilise-t-on après "si" dans une hypothèse?',
      options: ['Futur', 'Imparfait', 'Conditionnel', 'Subjonctif'],
      correctAnswer: 1,
      explanation: 'Après "si", on utilise l\'imparfait pour exprimer une hypothèse.',
    },
    {
      id: 'q2_7',
      question: 'Comment exprimer l\'opposition dans un texte?',
      options: ['Donc', 'Car', 'Cependant', 'Ainsi'],
      correctAnswer: 2,
      explanation: '"Cependant", "mais", "pourtant" expriment l\'opposition.',
    },
    {
      id: 'q2_8',
      question: 'Quelle structure exprime le but?',
      options: ['Parce que', 'Pour que', 'Quand', 'Si'],
      correctAnswer: 1,
      explanation: '"Pour que" (+ subjonctif) exprime le but.',
    },
    {
      id: 'q2_9',
      question: 'Dans un récit, quel temps utilise-t-on pour la description?',
      options: ['Passé simple', 'Imparfait', 'Futur', 'Présent'],
      correctAnswer: 1,
      explanation: 'L\'imparfait est utilisé pour les descriptions dans un récit au passé.',
    },
    {
      id: 'q2_10',
      question: 'Comment introduire un exemple dans un texte argumentatif?',
      options: ['Mais', 'Par exemple', 'Donc', 'Car'],
      correctAnswer: 1,
      explanation: '"Par exemple", "notamment", "ainsi" introduisent des exemples.',
    },
  ],

  // Paper 9: Expression Écrite - Niveau A2 (Beginner)
  '9': [
    {
      id: 'q9_1',
      question: 'Comment commence-t-on une lettre amicale?',
      options: ['Madame, Monsieur', 'Cher/Chère', 'À qui de droit', 'Bonjour Monsieur'],
      correctAnswer: 1,
      explanation: '"Cher/Chère + prénom" est approprié pour une lettre amicale.',
    },
    {
      id: 'q9_2',
      question: 'Quel mot utilise-t-on pour ajouter une information?',
      options: ['Mais', 'Et', 'Ou', 'Donc'],
      correctAnswer: 1,
      explanation: '"Et" permet d\'ajouter une information.',
    },
    {
      id: 'q9_3',
      question: 'Comment dit-on "I like" en français?',
      options: ['Je n\'aime pas', 'J\'aime', 'J\'adore', 'Je déteste'],
      correctAnswer: 1,
      explanation: '"J\'aime" signifie "I like".',
    },
    {
      id: 'q9_4',
      question: 'Quel mot exprime le temps?',
      options: ['Hier', 'Ici', 'Beaucoup', 'Très'],
      correctAnswer: 0,
      explanation: '"Hier" exprime le temps (le passé).',
    },
    {
      id: 'q9_5',
      question: 'Comment termine-t-on un email à un ami?',
      options: ['Cordialement', 'À bientôt', 'Veuillez agréer', 'Respectueusement'],
      correctAnswer: 1,
      explanation: '"À bientôt", "Bisous", "Amitiés" sont appropriés pour un ami.',
    },
    {
      id: 'q9_6',
      question: 'Quel est le pluriel de "journal"?',
      options: ['Journals', 'Journaux', 'Journales', 'Journal'],
      correctAnswer: 1,
      explanation: 'Le pluriel de "journal" est "journaux".',
    },
    {
      id: 'q9_7',
      question: 'Comment exprimer une préférence simple?',
      options: ['Je préfère', 'Je dois', 'Je peux', 'Je sais'],
      correctAnswer: 0,
      explanation: '"Je préfère" exprime une préférence.',
    },
    {
      id: 'q9_8',
      question: 'Quelle préposition utilise-t-on avec un pays féminin?',
      options: ['Au', 'En', 'À', 'Dans'],
      correctAnswer: 1,
      explanation: 'On utilise "en" avec les pays féminins: "en France".',
    },
    {
      id: 'q9_9',
      question: 'Comment faire une phrase négative simple?',
      options: ['Ne...pas', 'Ne...jamais seulement', 'Pas seulement', 'Non...oui'],
      correctAnswer: 0,
      explanation: '"Ne...pas" forme la négation de base: "Je ne veux pas".',
    },
    {
      id: 'q9_10',
      question: 'Quel article utilise-t-on devant un nom féminin singulier?',
      options: ['Le', 'La', 'Les', 'L\' seulement'],
      correctAnswer: 1,
      explanation: '"La" est l\'article féminin singulier: "la maison".',
    },
  ],

  // Paper 10: Expression Écrite - Niveau B2 (Advanced)
  '10': [
    {
      id: 'q10_1',
      question: 'Quel mode verbal suit "bien que"?',
      options: ['Indicatif', 'Subjonctif', 'Conditionnel', 'Infinitif'],
      correctAnswer: 1,
      explanation: '"Bien que" est toujours suivi du subjonctif.',
    },
    {
      id: 'q10_2',
      question: 'Comment exprimer une concession dans un texte argumentatif?',
      options: ['Donc', 'Certes...mais', 'Car', 'Ainsi'],
      correctAnswer: 1,
      explanation: '"Certes...mais", "bien que", "même si" expriment la concession.',
    },
    {
      id: 'q10_3',
      question: 'Quelle est la voix passive de "Le professeur corrige les copies"?',
      options: ['Les copies sont corrigées par le professeur', 'Les copies corrigent le professeur', 'Le professeur est corrigé', 'Les copies se corrigent'],
      correctAnswer: 0,
      explanation: 'La voix passive se forme avec "être + participe passé".',
    },
    {
      id: 'q10_4',
      question: 'Quel connecteur logique exprime la conséquence?',
      options: ['Puisque', 'Par conséquent', 'Malgré', 'Pendant que'],
      correctAnswer: 1,
      explanation: '"Par conséquent", "donc", "ainsi" expriment la conséquence.',
    },
    {
      id: 'q10_5',
      question: 'Dans un essai, comment introduire un point de vue opposé?',
      options: ['D\'abord', 'En revanche', 'Ensuite', 'Enfin'],
      correctAnswer: 1,
      explanation: '"En revanche", "au contraire", "néanmoins" introduisent un point de vue opposé.',
    },
    {
      id: 'q10_6',
      question: 'Quel temps utilise-t-on après "après que"?',
      options: ['Subjonctif', 'Indicatif', 'Conditionnel', 'Impératif'],
      correctAnswer: 1,
      explanation: '"Après que" est suivi de l\'indicatif (contrairement à "avant que").',
    },
    {
      id: 'q10_7',
      question: 'Comment nuancer une affirmation dans un texte formel?',
      options: ['Absolument', 'Il semblerait que', 'Certainement', 'Toujours'],
      correctAnswer: 1,
      explanation: '"Il semblerait que", "on pourrait penser que" nuancent une affirmation.',
    },
    {
      id: 'q10_8',
      question: 'Quelle structure exprime l\'antériorité?',
      options: ['Avant de + infinitif', 'Après + infinitif', 'Pour + infinitif', 'Sans + infinitif'],
      correctAnswer: 0,
      explanation: '"Avant de" exprime l\'antériorité avec un infinitif.',
    },
    {
      id: 'q10_9',
      question: 'Dans un discours indirect, "Il a dit: Je viendrai" devient:',
      options: ['Il a dit qu\'il viendrait', 'Il a dit qu\'il viendra', 'Il a dit je viendrai', 'Il a dit qu\'il vient'],
      correctAnswer: 0,
      explanation: 'Au discours indirect, le futur devient conditionnel après un temps passé.',
    },
    {
      id: 'q10_10',
      question: 'Quel est le rôle du participe présent dans "En travaillant dur, il réussira"?',
      options: ['Cause', 'Conséquence', 'But', 'Opposition'],
      correctAnswer: 0,
      explanation: 'Le gérondif "en + participe présent" peut exprimer la cause.',
    },
    {
      id: 'q10_11',
      question: 'Comment exprimer une hypothèse irréelle dans le passé?',
      options: ['Si + présent + futur', 'Si + imparfait + conditionnel présent', 'Si + plus-que-parfait + conditionnel passé', 'Si + passé composé + futur'],
      correctAnswer: 2,
      explanation: 'L\'hypothèse irréelle dans le passé: Si + plus-que-parfait + conditionnel passé.',
    },
    {
      id: 'q10_12',
      question: 'Quelle formule utilise-t-on pour conclure un essai?',
      options: ['D\'abord', 'Ensuite', 'En conclusion', 'Cependant'],
      correctAnswer: 2,
      explanation: '"En conclusion", "pour conclure", "en somme" introduisent la conclusion.',
    },
  ],

  // Paper 3: Compréhension Écrite - Niveau B2 (Advanced)
  '3': [
    {
      id: 'q3_1',
      question: 'Dans le texte: "Nonobstant les difficultés, le projet avance." Que signifie "nonobstant"?',
      options: ['À cause de', 'Malgré', 'Grâce à', 'Avec'],
      correctAnswer: 1,
      explanation: '"Nonobstant" est un terme formel signifiant "malgré".',
    },
    {
      id: 'q3_2',
      question: 'Quelle est l\'idée principale d\'un paragraphe argumentatif?',
      options: ['La dernière phrase', 'La première phrase généralement', 'Au milieu', 'Il n\'y en a pas'],
      correctAnswer: 1,
      explanation: 'La phrase-clé est souvent en début de paragraphe dans un texte argumentatif.',
    },
    {
      id: 'q3_3',
      question: 'Dans un texte, "en l\'occurrence" signifie:',
      options: ['Jamais', 'Dans ce cas précis', 'Toujours', 'Peut-être'],
      correctAnswer: 1,
      explanation: '"En l\'occurrence" signifie "dans ce cas particulier".',
    },
    {
      id: 'q3_4',
      question: 'Un texte qui présente des arguments pour et contre est:',
      options: ['Narratif', 'Descriptif', 'Dialectique', 'Poétique'],
      correctAnswer: 2,
      explanation: 'Un texte dialectique présente thèse, antithèse et synthèse.',
    },
    {
      id: 'q3_5',
      question: 'Que signifie "à l\'instar de"?',
      options: ['Contrairement à', 'Comme', 'Sans', 'Avant'],
      correctAnswer: 1,
      explanation: '"À l\'instar de" signifie "comme", "à la manière de".',
    },
    {
      id: 'q3_6',
      question: 'Dans un article de presse, le chapeau est:',
      options: ['Le titre', 'Le court résumé sous le titre', 'La conclusion', 'L\'auteur'],
      correctAnswer: 1,
      explanation: 'Le chapeau est le court texte qui résume l\'article sous le titre.',
    },
    {
      id: 'q3_7',
      question: 'Que signifie "de surcroît"?',
      options: ['En moins', 'En plus', 'Au contraire', 'Peut-être'],
      correctAnswer: 1,
      explanation: '"De surcroît" signifie "en plus", "de plus".',
    },
    {
      id: 'q3_8',
      question: 'Un euphémisme est:',
      options: ['Une exagération', 'Une atténuation', 'Une répétition', 'Une question'],
      correctAnswer: 1,
      explanation: 'Un euphémisme atténue une réalité désagréable.',
    },
    {
      id: 'q3_9',
      question: 'Dans "Il va de soi que", l\'expression signifie:',
      options: ['C\'est impossible', 'C\'est évident', 'C\'est douteux', 'C\'est rare'],
      correctAnswer: 1,
      explanation: '"Il va de soi" signifie "c\'est évident", "il est évident que".',
    },
    {
      id: 'q3_10',
      question: 'Que signifie "en somme"?',
      options: ['En détail', 'En résumé', 'En premier', 'En dernier'],
      correctAnswer: 1,
      explanation: '"En somme" signifie "en résumé", "pour résumer".',
    },
    {
      id: 'q3_11',
      question: 'Un texte qui raconte des événements réels passés est:',
      options: ['Une fiction', 'Un récit historique', 'Une utopie', 'Un conte'],
      correctAnswer: 1,
      explanation: 'Un récit historique relate des événements réels du passé.',
    },
    {
      id: 'q3_12',
      question: 'Dans "Force est de constater", que veut dire cette expression?',
      options: ['On peut ignorer', 'On doit reconnaître', 'On peut douter', 'On peut refuser'],
      correctAnswer: 1,
      explanation: '"Force est de constater" signifie "on doit reconnaître que".',
    },
  ],

  // Paper 11: Compréhension Écrite - Niveau A1 (Beginner)
  '11': [
    {
      id: 'q11_1',
      question: 'Lisez: "Le chat est sur le tapis." Où est le chat?',
      options: ['Sous le tapis', 'Sur le tapis', 'Devant le tapis', 'Derrière le tapis'],
      correctAnswer: 1,
      explanation: 'Le texte dit clairement que le chat est sur le tapis.',
    },
    {
      id: 'q11_2',
      question: 'Dans "Marie aime le chocolat", qui aime le chocolat?',
      options: ['Pierre', 'Marie', 'Jean', 'Sophie'],
      correctAnswer: 1,
      explanation: 'Marie est le sujet qui aime le chocolat.',
    },
    {
      id: 'q11_3',
      question: 'Lisez: "Il fait beau aujourd\'hui." Quel temps fait-il?',
      options: ['Il pleut', 'Il fait beau', 'Il neige', 'Il fait froid'],
      correctAnswer: 1,
      explanation: 'Le texte indique qu\'il fait beau.',
    },
    {
      id: 'q11_4',
      question: 'Dans "Je vais à l\'école", où va la personne?',
      options: ['Au parc', 'À l\'école', 'À la maison', 'Au magasin'],
      correctAnswer: 1,
      explanation: 'La personne va à l\'école.',
    },
    {
      id: 'q11_5',
      question: 'Lisez: "Pierre mange une pomme." Que mange Pierre?',
      options: ['Une orange', 'Une pomme', 'Une banane', 'Du pain'],
      correctAnswer: 1,
      explanation: 'Pierre mange une pomme.',
    },
    {
      id: 'q11_6',
      question: 'Dans "La voiture est rouge", de quelle couleur est la voiture?',
      options: ['Bleue', 'Verte', 'Rouge', 'Jaune'],
      correctAnswer: 2,
      explanation: 'La voiture est rouge.',
    },
    {
      id: 'q11_7',
      question: 'Lisez: "J\'ai deux frères." Combien de frères a la personne?',
      options: ['Un', 'Deux', 'Trois', 'Zéro'],
      correctAnswer: 1,
      explanation: 'La personne a deux frères.',
    },
    {
      id: 'q11_8',
      question: 'Dans "Elle habite à Paris", où habite-t-elle?',
      options: ['À Lyon', 'À Paris', 'À Marseille', 'À Nice'],
      correctAnswer: 1,
      explanation: 'Elle habite à Paris.',
    },
    {
      id: 'q11_9',
      question: 'Lisez: "Le livre est sur la table." Où est le livre?',
      options: ['Sous la table', 'Sur la table', 'Dans la table', 'À côté de la table'],
      correctAnswer: 1,
      explanation: 'Le livre est sur la table.',
    },
    {
      id: 'q11_10',
      question: 'Dans "Mon chien s\'appelle Max", comment s\'appelle le chien?',
      options: ['Rex', 'Max', 'Tom', 'Bob'],
      correctAnswer: 1,
      explanation: 'Le chien s\'appelle Max.',
    },
  ],

  // Paper 12: Compréhension Écrite - Niveau B1 (Intermediate)
  '12': [
    {
      id: 'q12_1',
      question: 'Dans un texte sur l\'environnement mentionnant "le développement durable", cela fait référence à:',
      options: ['La croissance rapide', 'Un développement qui préserve les ressources', 'L\'industrie', 'La technologie'],
      correctAnswer: 1,
      explanation: 'Le développement durable vise à répondre aux besoins actuels sans compromettre l\'avenir.',
    },
    {
      id: 'q12_2',
      question: 'Un article dit: "Les jeunes sont de plus en plus connectés." Que signifie cette phrase?',
      options: ['Ils ont moins d\'amis', 'Ils utilisent plus Internet', 'Ils lisent plus', 'Ils sortent plus'],
      correctAnswer: 1,
      explanation: '"Connectés" fait référence à l\'utilisation d\'Internet et des réseaux sociaux.',
    },
    {
      id: 'q12_3',
      question: 'Dans un guide touristique: "Il est recommandé de réserver à l\'avance." Que devez-vous faire?',
      options: ['Arriver tôt', 'Réserver avant de venir', 'Payer plus cher', 'Annuler'],
      correctAnswer: 1,
      explanation: '"Réserver à l\'avance" signifie réserver avant votre visite.',
    },
    {
      id: 'q12_4',
      question: 'Un article mentionne "la crise économique". De quoi parle-t-on?',
      options: ['Une période de croissance', 'Des difficultés économiques', 'Une réussite', 'Un festival'],
      correctAnswer: 1,
      explanation: 'Une crise économique est une période de difficultés économiques.',
    },
    {
      id: 'q12_5',
      question: 'Dans "Ce produit est respectueux de l\'environnement", que signifie cette description?',
      options: ['Il coûte cher', 'Il ne pollue pas', 'Il est nouveau', 'Il est grand'],
      correctAnswer: 1,
      explanation: '"Respectueux de l\'environnement" signifie écologique, qui ne nuit pas à l\'environnement.',
    },
    {
      id: 'q12_6',
      question: 'Un texte dit: "Les mesures prises ont porté leurs fruits." Que s\'est-il passé?',
      options: ['Rien n\'a changé', 'Les mesures ont réussi', 'Les mesures ont échoué', 'On a planté des arbres'],
      correctAnswer: 1,
      explanation: '"Porter ses fruits" signifie avoir des résultats positifs.',
    },
    {
      id: 'q12_7',
      question: 'Dans une offre d\'emploi: "Expérience souhaitée". Que veut dire l\'entreprise?',
      options: ['L\'expérience est obligatoire', 'L\'expérience est un plus', 'Pas d\'expérience nécessaire', 'Beaucoup d\'expérience requise'],
      correctAnswer: 1,
      explanation: '"Souhaitée" signifie préférée mais pas obligatoire (contrairement à "requise").',
    },
    {
      id: 'q12_8',
      question: 'Un article mentionne "l\'essor du télétravail". Que signifie "essor"?',
      options: ['La fin', 'Le développement', 'Le problème', 'L\'interdiction'],
      correctAnswer: 1,
      explanation: '"L\'essor" signifie le développement, la croissance.',
    },
    {
      id: 'q12_9',
      question: 'Dans "Cette décision suscite la polémique", que provoque la décision?',
      options: ['L\'accord de tous', 'Un débat controversé', 'De la joie', 'De l\'indifférence'],
      correctAnswer: 1,
      explanation: '"Susciter la polémique" signifie provoquer un débat, des désaccords.',
    },
    {
      id: 'q12_10',
      question: 'Un texte dit: "Il faut prendre en compte plusieurs facteurs." Que doit-on faire?',
      options: ['Ignorer les détails', 'Considérer plusieurs éléments', 'Agir vite', 'Compter'],
      correctAnswer: 1,
      explanation: '"Prendre en compte" signifie considérer, tenir compte de.',
    },
    {
      id: 'q12_11',
      question: 'Dans "Cette entreprise recrute en masse", que fait l\'entreprise?',
      options: ['Licencie', 'Embauche beaucoup', 'Ferme', 'Déménage'],
      correctAnswer: 1,
      explanation: '"Recruter en masse" signifie embaucher beaucoup de personnes.',
    },
    {
      id: 'q12_12',
      question: 'Un article parle de "la montée en puissance de l\'IA". Que se passe-t-il?',
      options: ['L\'IA disparaît', 'L\'IA se développe rapidement', 'L\'IA est interdite', 'L\'IA coûte cher'],
      correctAnswer: 1,
      explanation: '"Montée en puissance" signifie développement rapide et important.',
    },
  ],

  // Paper 5: Expression Orale - Niveau B2 (Advanced)
  '5': [
    {
      id: 'q5_1',
      question: 'Pour exprimer un désaccord poliment, quelle phrase est appropriée?',
      options: ['Tu as tort!', 'Je ne suis pas tout à fait d\'accord', 'C\'est faux', 'N\'importe quoi'],
      correctAnswer: 1,
      explanation: '"Je ne suis pas tout à fait d\'accord" est une façon polie d\'exprimer un désaccord.',
    },
    {
      id: 'q5_2',
      question: 'Pour prendre la parole dans un débat, on peut dire:',
      options: ['Tais-toi!', 'Si je peux me permettre...', 'Arrête!', 'Faux!'],
      correctAnswer: 1,
      explanation: '"Si je peux me permettre" est une formule polie pour intervenir.',
    },
    {
      id: 'q5_3',
      question: 'Pour nuancer son opinion, quelle expression utiliser?',
      options: ['Absolument', 'Il me semble que', 'Certainement', 'Toujours'],
      correctAnswer: 1,
      explanation: '"Il me semble que", "je pense que" nuancent une opinion.',
    },
    {
      id: 'q5_4',
      question: 'Comment reformuler poliment quand on n\'a pas compris?',
      options: ['Quoi?', 'Pourriez-vous préciser?', 'Je ne comprends rien', 'Parle mieux'],
      correctAnswer: 1,
      explanation: '"Pourriez-vous préciser?" est une demande polie de clarification.',
    },
    {
      id: 'q5_5',
      question: 'Pour conclure une présentation orale:',
      options: ['C\'est fini', 'Pour conclure', 'Stop', 'Voilà voilà'],
      correctAnswer: 1,
      explanation: '"Pour conclure", "en conclusion" introduisent la conclusion.',
    },
    {
      id: 'q5_6',
      question: 'Pour exprimer une hypothèse à l\'oral:',
      options: ['C\'est sûr', 'On peut supposer que', 'C\'est certain', 'Sans doute pas'],
      correctAnswer: 1,
      explanation: '"On peut supposer", "il se pourrait que" expriment une hypothèse.',
    },
    {
      id: 'q5_7',
      question: 'Pour donner son avis dans un contexte formel:',
      options: ['Je pense', 'À mon avis', 'Selon moi', 'Toutes ces réponses'],
      correctAnswer: 3,
      explanation: 'Toutes ces expressions permettent de donner son avis formellement.',
    },
    {
      id: 'q5_8',
      question: 'Pour interrompre poliment quelqu\'un:',
      options: ['Stop!', 'Excusez-moi de vous interrompre', 'Tais-toi', 'Arrête de parler'],
      correctAnswer: 1,
      explanation: '"Excusez-moi de vous interrompre" est la façon polie d\'interrompre.',
    },
    {
      id: 'q5_9',
      question: 'Pour illustrer son propos avec un exemple:',
      options: ['Comme', 'Par exemple', 'Donc', 'Mais'],
      correctAnswer: 1,
      explanation: '"Par exemple", "notamment", "ainsi" introduisent des exemples.',
    },
    {
      id: 'q5_10',
      question: 'Pour exprimer son accord partiel:',
      options: ['Oui, mais', 'Non', 'Jamais', 'Toujours'],
      correctAnswer: 0,
      explanation: '"Oui, mais" exprime un accord partiel avec une réserve.',
    },
    {
      id: 'q5_11',
      question: 'Pour gagner du temps de réflexion à l\'oral:',
      options: ['Euh...', 'C\'est une question intéressante', 'Je ne sais pas', 'Silence'],
      correctAnswer: 1,
      explanation: '"C\'est une question intéressante" ou "Voyons voir" permettent de réfléchir.',
    },
    {
      id: 'q5_12',
      question: 'Pour structurer un discours, quelle expression utiliser en premier?',
      options: ['Enfin', 'D\'abord', 'Donc', 'Ainsi'],
      correctAnswer: 1,
      explanation: '"D\'abord", "tout d\'abord", "premièrement" commencent une énumération.',
    },
  ],

  // Paper 13: Expression Orale - Niveau A2/B1 (Intermediate)
  '13': [
    {
      id: 'q13_1',
      question: 'Comment demander poliment une information?',
      options: ['Dis-moi!', 'Pourriez-vous me dire?', 'Donne l\'info', 'Parle!'],
      correctAnswer: 1,
      explanation: '"Pourriez-vous me dire" est une formule polie pour demander.',
    },
    {
      id: 'q13_2',
      question: 'Pour exprimer son accord:',
      options: ['Non', 'Je suis d\'accord', 'Jamais', 'Peut-être pas'],
      correctAnswer: 1,
      explanation: '"Je suis d\'accord", "tout à fait" expriment l\'accord.',
    },
    {
      id: 'q13_3',
      question: 'Comment proposer quelque chose à quelqu\'un?',
      options: ['Tu dois', 'On pourrait', 'Tu vas', 'Fais-le'],
      correctAnswer: 1,
      explanation: '"On pourrait", "et si on..." proposent une activité.',
    },
    {
      id: 'q13_4',
      question: 'Pour demander l\'avis de quelqu\'un:',
      options: ['Qu\'est-ce que tu penses?', 'Tais-toi', 'C\'est nul', 'Je ne veux pas savoir'],
      correctAnswer: 0,
      explanation: '"Qu\'est-ce que tu penses?" ou "Quel est ton avis?" demandent l\'opinion.',
    },
    {
      id: 'q13_5',
      question: 'Comment refuser poliment une invitation?',
      options: ['Non!', 'Je regrette, je ne peux pas', 'Jamais', 'C\'est nul'],
      correctAnswer: 1,
      explanation: '"Je regrette" ou "Je suis désolé" permettent de refuser poliment.',
    },
    {
      id: 'q13_6',
      question: 'Pour exprimer une préférence:',
      options: ['Je préfère', 'Je déteste', 'Je dois', 'Je peux'],
      correctAnswer: 0,
      explanation: '"Je préfère", "j\'aime mieux" expriment une préférence.',
    },
    {
      id: 'q13_7',
      question: 'Comment demander de répéter?',
      options: ['Quoi?', 'Pardon, pouvez-vous répéter?', 'Parle mieux', 'Je ne comprends rien'],
      correctAnswer: 1,
      explanation: '"Pardon, pouvez-vous répéter?" est la demande polie.',
    },
    {
      id: 'q13_8',
      question: 'Pour parler de ses projets futurs:',
      options: ['J\'ai fait', 'Je vais faire', 'Je faisais', 'Je ferais peut-être'],
      correctAnswer: 1,
      explanation: '"Je vais + infinitif" exprime le futur proche.',
    },
    {
      id: 'q13_9',
      question: 'Comment exprimer son enthousiasme?',
      options: ['C\'est nul', 'C\'est génial!', 'Je déteste', 'C\'est terrible'],
      correctAnswer: 1,
      explanation: '"C\'est génial!", "super!", "formidable!" expriment l\'enthousiasme.',
    },
    {
      id: 'q13_10',
      question: 'Pour raconter une anecdote, on commence par:',
      options: ['La fin', 'Un jour', 'Donc', 'Jamais'],
      correctAnswer: 1,
      explanation: '"Un jour", "l\'autre jour", "hier" commencent un récit.',
    },
  ],

  // Paper 4: Vocabulaire et Grammaire - A2 (Beginner)
  '4': [
    {
      id: 'q4_1',
      question: 'Complétez: "Je ___ français."',
      options: ['parle', 'parles', 'parlons', 'parlent'],
      correctAnswer: 0,
      explanation: 'Avec "je", on utilise "parle" (première personne du singulier).',
    },
    {
      id: 'q4_2',
      question: 'Quel est le féminin de "acteur"?',
      options: ['Acteure', 'Actrice', 'Acteuresse', 'Actrice'],
      correctAnswer: 1,
      explanation: 'Le féminin de "acteur" est "actrice".',
    },
    {
      id: 'q4_3',
      question: 'Complétez: "Nous ___ au cinéma."',
      options: ['va', 'vas', 'allons', 'vont'],
      correctAnswer: 2,
      explanation: 'Avec "nous", on utilise "allons" (première personne du pluriel).',
    },
    {
      id: 'q4_4',
      question: 'Quel article devant "école"?',
      options: ['Le', 'La', 'Les', 'Un'],
      correctAnswer: 1,
      explanation: '"École" est féminin, donc "l\'école" ou "la école" → "l\'école".',
    },
    {
      id: 'q4_5',
      question: 'Complétez: "Ils ___ contents."',
      options: ['est', 'es', 'sommes', 'sont'],
      correctAnswer: 3,
      explanation: 'Avec "ils", on utilise "sont" (troisième personne du pluriel).',
    },
    {
      id: 'q4_6',
      question: 'Quel est le contraire de "grand"?',
      options: ['Gros', 'Petit', 'Long', 'Large'],
      correctAnswer: 1,
      explanation: 'Le contraire de "grand" est "petit".',
    },
    {
      id: 'q4_7',
      question: 'Complétez: "Elle ___ une voiture rouge."',
      options: ['a', 'as', 'ont', 'avons'],
      correctAnswer: 0,
      explanation: 'Avec "elle", on utilise "a" (troisième personne du singulier).',
    },
    {
      id: 'q4_8',
      question: 'Quelle préposition avec "aller" + lieu?',
      options: ['De', 'À', 'En', 'Pour'],
      correctAnswer: 1,
      explanation: 'On dit "aller à" + lieu: "Je vais à Paris".',
    },
    {
      id: 'q4_9',
      question: 'Complétez: "Tu ___ quel âge?"',
      options: ['a', 'as', 'ont', 'est'],
      correctAnswer: 1,
      explanation: 'On dit "tu as quel âge?" (verbe avoir).',
    },
    {
      id: 'q4_10',
      question: 'Quel est le pluriel de "cheval"?',
      options: ['Chevals', 'Chevaux', 'Chevales', 'Cheval'],
      correctAnswer: 1,
      explanation: 'Le pluriel de "cheval" est "chevaux".',
    },
    {
      id: 'q4_11',
      question: 'Complétez: "Marie et Paul ___ frères."',
      options: ['est', 'es', 'sont', 'sommes'],
      correctAnswer: 2,
      explanation: 'Avec un sujet pluriel, on utilise "sont".',
    },
    {
      id: 'q4_12',
      question: 'Quel mot signifie "expensive"?',
      options: ['Bon marché', 'Cher', 'Gratuit', 'Pas cher'],
      correctAnswer: 1,
      explanation: '"Cher" signifie "expensive" en français.',
    },
  ],

  // Paper 14: Vocabulaire et Grammaire - A1 (Beginner)
  '14': [
    {
      id: 'q14_1',
      question: 'Je ___ un étudiant.',
      options: ['es', 'suis', 'est', 'sommes'],
      correctAnswer: 1,
      explanation: 'Avec "je", on utilise "suis" (verbe être).',
    },
    {
      id: 'q14_2',
      question: 'Quel article devant "livre"?',
      options: ['La', 'Le', 'Les', 'L\''],
      correctAnswer: 1,
      explanation: '"Livre" est masculin, donc "le livre".',
    },
    {
      id: 'q14_3',
      question: 'Comment dit-on "one" en français?',
      options: ['Un', 'Deux', 'Trois', 'Quatre'],
      correctAnswer: 0,
      explanation: '"Un" signifie "one" en français.',
    },
    {
      id: 'q14_4',
      question: 'Complétez: "Tu ___ français?"',
      options: ['parle', 'parles', 'parlons', 'parlent'],
      correctAnswer: 1,
      explanation: 'Avec "tu", on utilise "parles" (deuxième personne du singulier).',
    },
    {
      id: 'q14_5',
      question: 'Quel mot signifie "cat"?',
      options: ['Chien', 'Chat', 'Oiseau', 'Poisson'],
      correctAnswer: 1,
      explanation: '"Chat" signifie "cat" en français.',
    },
    {
      id: 'q14_6',
      question: 'Complétez: "Elle ___ belle."',
      options: ['est', 'es', 'sommes', 'sont'],
      correctAnswer: 0,
      explanation: 'Avec "elle", on utilise "est" (troisième personne du singulier).',
    },
    {
      id: 'q14_7',
      question: 'Comment dit-on "blue" en français?',
      options: ['Rouge', 'Vert', 'Bleu', 'Jaune'],
      correctAnswer: 2,
      explanation: '"Bleu" signifie "blue" en français.',
    },
    {
      id: 'q14_8',
      question: 'Complétez: "Nous ___ français."',
      options: ['parle', 'parles', 'parlons', 'parlent'],
      correctAnswer: 2,
      explanation: 'Avec "nous", on utilise "parlons".',
    },
    {
      id: 'q14_9',
      question: 'Quel est le féminin de "ami"?',
      options: ['Amie', 'Amis', 'Amies', 'Amie'],
      correctAnswer: 0,
      explanation: 'Le féminin de "ami" est "amie".',
    },
    {
      id: 'q14_10',
      question: 'Comment dit-on "big" en français?',
      options: ['Petit', 'Grand', 'Moyen', 'Gros'],
      correctAnswer: 1,
      explanation: '"Grand" signifie "big" ou "tall" en français.',
    },
  ],

  // Paper 15: Vocabulaire et Grammaire - B1 (Intermediate)
  '15': [
    {
      id: 'q15_1',
      question: 'Complétez avec le bon temps: "Hier, je ___ au cinéma."',
      options: ['vais', 'suis allé', 'irai', 'irais'],
      correctAnswer: 1,
      explanation: '"Hier" indique le passé, donc passé composé "suis allé".',
    },
    {
      id: 'q15_2',
      question: 'Quel pronom relatif: "Le livre ___ je lis est intéressant."',
      options: ['qui', 'que', 'où', 'dont'],
      correctAnswer: 1,
      explanation: '"Que" est COD: "je lis le livre" → "le livre que je lis".',
    },
    {
      id: 'q15_3',
      question: 'Complétez: "Si j\'___ riche, je voyagerais."',
      options: ['suis', 'étais', 'serais', 'serai'],
      correctAnswer: 1,
      explanation: 'Après "si" hypothétique, on utilise l\'imparfait.',
    },
    {
      id: 'q15_4',
      question: 'Quel temps après "quand" + futur: "Quand je ___ , je te téléphonerai."',
      options: ['arrive', 'arriverai', 'arrivais', 'suis arrivé'],
      correctAnswer: 1,
      explanation: 'Avec "quand" + futur, on utilise le futur dans les deux parties.',
    },
    {
      id: 'q15_5',
      question: 'Complétez: "Il faut que tu ___ ."',
      options: ['viens', 'viennes', 'venir', 'venais'],
      correctAnswer: 1,
      explanation: 'Après "il faut que", on utilise le subjonctif: "viennes".',
    },
    {
      id: 'q15_6',
      question: 'Quel pronom: "Je parle à Marie" → "Je ___ parle."',
      options: ['la', 'le', 'lui', 'leur'],
      correctAnswer: 2,
      explanation: '"Parler à quelqu\'un" → pronom indirect "lui".',
    },
    {
      id: 'q15_7',
      question: 'Complétez: "Nous sommes ___ hier."',
      options: ['parti', 'partis', 'partie', 'parties'],
      correctAnswer: 1,
      explanation: 'Avec "nous" (accord masculin pluriel ou mixte): "partis".',
    },
    {
      id: 'q15_8',
      question: 'Quel est le participe passé de "prendre"?',
      options: ['Prenu', 'Pris', 'Prendu', 'Prendre'],
      correctAnswer: 1,
      explanation: 'Le participe passé de "prendre" est irrégulier: "pris".',
    },
    {
      id: 'q15_9',
      question: 'Complétez: "Je ne vois ___ ."',
      options: ['personne', 'rien', 'jamais', 'plus'],
      correctAnswer: 0,
      explanation: '"Je ne vois personne" = I don\'t see anyone.',
    },
    {
      id: 'q15_10',
      question: 'Quelle préposition: "Je suis intéressé ___ ce sujet."',
      options: ['à', 'de', 'par', 'pour'],
      correctAnswer: 2,
      explanation: '"Être intéressé par" est la construction correcte.',
    },
    {
      id: 'q15_11',
      question: 'Complétez: "Avant de ___ , lave-toi les mains."',
      options: ['manges', 'manger', 'mangé', 'mangeant'],
      correctAnswer: 1,
      explanation: 'Après "avant de", on utilise l\'infinitif.',
    },
    {
      id: 'q15_12',
      question: 'Quel adverbe correspond à "lent"?',
      options: ['Lentement', 'Lente', 'Lentitude', 'Lentemment'],
      correctAnswer: 0,
      explanation: 'L\'adverbe de "lent" est "lentement".',
    },
  ],

  // Paper 6: Test Complet - Niveau B1 (Intermediate) - 15 questions diverses
  '6': [
    {
      id: 'q6_1',
      question: 'Complétez: "Je voudrais ___ rendez-vous chez le dentiste."',
      options: ['prendre', 'faire', 'donner', 'avoir'],
      correctAnswer: 0,
      explanation: '"Prendre un rendez-vous" est l\'expression correcte.',
    },
    {
      id: 'q6_2',
      question: 'Que signifie "avoir le coup de foudre"?',
      options: ['Avoir peur', 'Tomber amoureux immédiatement', 'Être en colère', 'Être fatigué'],
      correctAnswer: 1,
      explanation: '"Le coup de foudre" signifie tomber amoureux instantanément.',
    },
    {
      id: 'q6_3',
      question: 'Complétez: "Il est important ___ tu viennes."',
      options: ['que', 'de', 'à', 'pour'],
      correctAnswer: 0,
      explanation: '"Il est important que" + subjonctif.',
    },
    {
      id: 'q6_4',
      question: 'Dans "Elle s\'est lavé les mains", pourquoi pas "lavée"?',
      options: ['Erreur, c\'est "lavée"', 'Le COD est "les mains", pas "elle"', 'Verbe intransitif', 'Au hasard'],
      correctAnswer: 1,
      explanation: 'Le COD "les mains" est après le verbe, donc pas d\'accord.',
    },
    {
      id: 'q6_5',
      question: 'Que veut dire "en avoir marre"?',
      options: ['Être content', 'En avoir assez', 'Avoir faim', 'Avoir soif'],
      correctAnswer: 1,
      explanation: '"En avoir marre" signifie être fatigué de quelque chose.',
    },
    {
      id: 'q6_6',
      question: 'Complétez: "C\'est le film ___ je t\'ai parlé."',
      options: ['que', 'qui', 'dont', 'où'],
      correctAnswer: 2,
      explanation: '"Parler de quelque chose" → "dont" (de + relatif).',
    },
    {
      id: 'q6_7',
      question: 'Quel temps: "Quand j\'étais petit, je ___ au foot."',
      options: ['joue', 'jouais', 'ai joué', 'jouerai'],
      correctAnswer: 1,
      explanation: 'Habitude dans le passé = imparfait "jouais".',
    },
    {
      id: 'q6_8',
      question: 'Complétez: "Je regrette qu\'il ne ___ pas venu."',
      options: ['est', 'soit', 'a', 'était'],
      correctAnswer: 1,
      explanation: 'Après "regretter que", subjonctif passé: "soit venu".',
    },
    {
      id: 'q6_9',
      question: 'Que signifie "poser un lapin à quelqu\'un"?',
      options: ['Donner un lapin', 'Ne pas venir à un rendez-vous', 'Être gentil', 'Cuisiner'],
      correctAnswer: 1,
      explanation: '"Poser un lapin" signifie ne pas venir à un rendez-vous.',
    },
    {
      id: 'q6_10',
      question: 'Complétez: "___ il pleuve, nous irons au parc."',
      options: ['Si', 'Quand', 'Bien que', 'Parce que'],
      correctAnswer: 2,
      explanation: '"Bien que" + subjonctif exprime la concession.',
    },
    {
      id: 'q6_11',
      question: 'Quel pronom: "Donne le livre à Pierre" → "Donne- ___ ."',
      options: ['le-lui', 'lui-le', 'le-le', 'lui-lui'],
      correctAnswer: 0,
      explanation: 'COD avant COI à l\'impératif affirmatif: "donne-le-lui".',
    },
    {
      id: 'q6_12',
      question: 'Complétez: "Je l\'ai ___ hier." (voir, féminin)',
      options: ['vu', 'vue', 'vus', 'vues'],
      correctAnswer: 1,
      explanation: 'COD "l\'" (féminin) avant le verbe → accord: "vue".',
    },
    {
      id: 'q6_13',
      question: 'Que veut dire "il ne faut pas mettre la charrue avant les bœufs"?',
      options: ['Il faut travailler', 'Il ne faut pas faire les choses dans le désordre', 'Il faut être agriculteur', 'Il faut être patient'],
      correctAnswer: 1,
      explanation: 'Cette expression signifie qu\'il faut respecter l\'ordre logique des choses.',
    },
    {
      id: 'q6_14',
      question: 'Complétez: "Après ___ mangé, il est parti."',
      options: ['avoir', 'être', 'avons', 'étant'],
      correctAnswer: 0,
      explanation: '"Après" + infinitif passé: "après avoir mangé".',
    },
    {
      id: 'q6_15',
      question: 'Dans un contexte formel, comment dire "Je veux"?',
      options: ['Je veux', 'Je voudrais', 'Je désire', 'Je souhaiterais'],
      correctAnswer: 3,
      explanation: '"Je souhaiterais" ou "je voudrais" sont plus polis que "je veux".',
    },
  ],

  // Paper 16: Test Complet - Niveau A2 (Beginner) - 12 questions
  '16': [
    {
      id: 'q16_1',
      question: 'Complétez: "J\' ___ froid."',
      options: ['suis', 'ai', 'fais', 'est'],
      correctAnswer: 1,
      explanation: 'On dit "avoir froid", pas "être froid".',
    },
    {
      id: 'q16_2',
      question: 'Quel jour vient avant dimanche?',
      options: ['Lundi', 'Vendredi', 'Samedi', 'Jeudi'],
      correctAnswer: 2,
      explanation: 'Samedi vient avant dimanche.',
    },
    {
      id: 'q16_3',
      question: 'Complétez: "Marie ___ à la bibliothèque."',
      options: ['va', 'vas', 'vont', 'aller'],
      correctAnswer: 0,
      explanation: 'Avec "Marie" (elle), on utilise "va".',
    },
    {
      id: 'q16_4',
      question: 'Comment demander l\'heure?',
      options: ['Quelle heure est-il?', 'Combien l\'heure?', 'Où l\'heure?', 'Qui l\'heure?'],
      correctAnswer: 0,
      explanation: '"Quelle heure est-il?" est la question correcte.',
    },
    {
      id: 'q16_5',
      question: 'Quel article devant "pomme"?',
      options: ['Le', 'La', 'Un', 'Une'],
      correctAnswer: 3,
      explanation: '"Pomme" est féminin, donc "une pomme".',
    },
    {
      id: 'q16_6',
      question: 'Complétez: "Ils ___ contents."',
      options: ['est', 'es', 'sont', 'sommes'],
      correctAnswer: 2,
      explanation: 'Avec "ils", on utilise "sont".',
    },
    {
      id: 'q16_7',
      question: 'Quelle saison après l\'été?',
      options: ['Printemps', 'Hiver', 'Automne', 'Été'],
      correctAnswer: 2,
      explanation: 'L\'automne vient après l\'été.',
    },
    {
      id: 'q16_8',
      question: 'Complétez: "Nous ___ une maison."',
      options: ['a', 'as', 'avons', 'ont'],
      correctAnswer: 2,
      explanation: 'Avec "nous", on utilise "avons".',
    },
    {
      id: 'q16_9',
      question: 'Comment dit-on "I\'m hungry" en français?',
      options: ['Je suis faim', 'J\'ai faim', 'Je fais faim', 'Je faim'],
      correctAnswer: 1,
      explanation: 'On dit "avoir faim" en français.',
    },
    {
      id: 'q16_10',
      question: 'Quel mot signifie "morning"?',
      options: ['Soir', 'Matin', 'Nuit', 'Après-midi'],
      correctAnswer: 1,
      explanation: '"Matin" signifie "morning".',
    },
    {
      id: 'q16_11',
      question: 'Complétez: "Tu ___ où?"',
      options: ['habite', 'habites', 'habitons', 'habitent'],
      correctAnswer: 1,
      explanation: 'Avec "tu", on utilise "habites".',
    },
    {
      id: 'q16_12',
      question: 'Quel est le contraire de "chaud"?',
      options: ['Froid', 'Tiède', 'Chaud', 'Brûlant'],
      correctAnswer: 0,
      explanation: 'Le contraire de "chaud" est "froid".',
    },
  ],
};

export const MOCK_PAPERS: Paper[] = [
  // Compréhension Orale (3 papers)
  {
    id: '1',
    title: 'TEF Compréhension Orale - Niveau A1',
    description: 'Test complet de compréhension orale pour débutants. Évaluez votre capacité à comprendre le français parlé dans des situations quotidiennes.',
    category: 'Compréhension Orale',
    difficulty: 'Beginner',
    duration: 30,
    questionsCount: 3,
    thumbnail: 'https://via.placeholder.com/400x250/5B21B6/ffffff?text=Oral+A1',
    isPremium: false,
  },
  {
    id: '7',
    title: 'TEF Compréhension Orale - Niveau A2',
    description: 'Développez vos compétences d\'écoute avec des dialogues et conversations du quotidien.',
    category: 'Compréhension Orale',
    difficulty: 'Beginner',
    duration: 35,
    questionsCount: 28,
    thumbnail: 'https://via.placeholder.com/400x250/6D28D9/ffffff?text=Oral+A2',
    isPremium: false,
  },
  {
    id: '8',
    title: 'TEF Compréhension Orale - Niveau B1',
    description: 'Comprenez des conversations plus complexes sur des sujets familiers et professionnels.',
    category: 'Compréhension Orale',
    difficulty: 'Intermediate',
    duration: 40,
    questionsCount: 32,
    thumbnail: 'https://via.placeholder.com/400x250/7C3AED/ffffff?text=Oral+B1',
    isPremium: true,
  },

  // Expression Écrite (3 papers)
  {
    id: '2',
    title: 'TEF Expression Écrite - Niveau B1',
    description: 'Pratiquez votre expression écrite avec des exercices intermédiaires. Incluant des questions sur la grammaire et la composition.',
    category: 'Expression Écrite',
    difficulty: 'Intermediate',
    duration: 45,
    questionsCount: 1,
    thumbnail: 'https://via.placeholder.com/400x250/7C3AED/ffffff?text=Ecrit+B1',
    isPremium: true,
  },
  {
    id: '9',
    title: 'TEF Expression Écrite - Niveau A2',
    description: 'Exercices d\'écriture pour débutants: emails simples, messages courts et descriptions basiques.',
    category: 'Expression Écrite',
    difficulty: 'Beginner',
    duration: 30,
    questionsCount: 20,
    thumbnail: 'https://via.placeholder.com/400x250/8B5CF6/ffffff?text=Ecrit+A2',
    isPremium: false,
  },
  {
    id: '10',
    title: 'TEF Expression Écrite - Niveau B2',
    description: 'Rédaction de textes argumentatifs et descriptions détaillées pour niveau avancé.',
    category: 'Expression Écrite',
    difficulty: 'Advanced',
    duration: 50,
    questionsCount: 35,
    thumbnail: 'https://via.placeholder.com/400x250/9333EA/ffffff?text=Ecrit+B2',
    isPremium: true,
  },

  // Compréhension Écrite (3 papers)
  {
    id: '3',
    title: 'TEF Compréhension Écrite - Niveau B2',
    description: 'Questions de compréhension de texte de niveau avancé. Testez votre capacité à comprendre des documents complexes.',
    category: 'Compréhension Écrite',
    difficulty: 'Advanced',
    duration: 60,
    questionsCount: 40,
    thumbnail: 'https://via.placeholder.com/400x250/3B82F6/ffffff?text=Lecture+B2',
    isPremium: true,
  },
  {
    id: '11',
    title: 'TEF Compréhension Écrite - Niveau A1',
    description: 'Lecture de textes simples: annonces, messages courts et instructions basiques.',
    category: 'Compréhension Écrite',
    difficulty: 'Beginner',
    duration: 25,
    questionsCount: 20,
    thumbnail: 'https://via.placeholder.com/400x250/2563EB/ffffff?text=Lecture+A1',
    isPremium: false,
  },
  {
    id: '12',
    title: 'TEF Compréhension Écrite - Niveau B1',
    description: 'Compréhension de textes informatifs, articles de presse et correspondances formelles.',
    category: 'Compréhension Écrite',
    difficulty: 'Intermediate',
    duration: 45,
    questionsCount: 30,
    thumbnail: 'https://via.placeholder.com/400x250/1D4ED8/ffffff?text=Lecture+B1',
    isPremium: true,
  },

  // Expression Orale (2 papers)
  {
    id: '5',
    title: 'TEF Expression Orale - Niveau B2',
    description: 'Préparez-vous pour la section d\'expression orale avec des questions et situations réelles.',
    category: 'Expression Orale',
    difficulty: 'Advanced',
    duration: 35,
    questionsCount: 20,
    thumbnail: 'https://via.placeholder.com/400x250/F59E0B/ffffff?text=Oral+B2',
    isPremium: true,
  },
  {
    id: '13',
    title: 'TEF Expression Orale - Niveau A2/B1',
    description: 'Entraînez-vous à parler sur des sujets familiers et à donner votre opinion.',
    category: 'Expression Orale',
    difficulty: 'Intermediate',
    duration: 25,
    questionsCount: 15,
    thumbnail: 'https://via.placeholder.com/400x250/D97706/ffffff?text=Oral+A2',
    isPremium: true,
  },

  // Vocabulaire et Grammaire (3 papers)
  {
    id: '4',
    title: 'TEF Vocabulaire et Grammaire - A2',
    description: 'Renforcez vos connaissances en vocabulaire et grammaire française. Parfait pour le niveau élémentaire.',
    category: 'Vocabulaire et Grammaire',
    difficulty: 'Beginner',
    duration: 40,
    questionsCount: 35,
    thumbnail: 'https://via.placeholder.com/400x250/10B981/ffffff?text=Vocab+A2',
    isPremium: false,
  },
  {
    id: '14',
    title: 'TEF Vocabulaire et Grammaire - A1',
    description: 'Les bases essentielles: conjugaisons simples, vocabulaire courant et structure de phrases.',
    category: 'Vocabulaire et Grammaire',
    difficulty: 'Beginner',
    duration: 30,
    questionsCount: 25,
    thumbnail: 'https://via.placeholder.com/400x250/059669/ffffff?text=Vocab+A1',
    isPremium: false,
  },
  {
    id: '15',
    title: 'TEF Vocabulaire et Grammaire - B1',
    description: 'Grammaire intermédiaire: temps verbaux complexes, pronoms et expressions idiomatiques.',
    category: 'Vocabulaire et Grammaire',
    difficulty: 'Intermediate',
    duration: 50,
    questionsCount: 40,
    thumbnail: 'https://via.placeholder.com/400x250/047857/ffffff?text=Vocab+B1',
    isPremium: true,
  },

  // Test Complet (2 papers)
  {
    id: '6',
    title: 'TEF Test Complet - Niveau B1',
    description: 'Simulation complète du TEF couvrant toutes les sections. Idéal pour préparer l\'examen officiel.',
    category: 'Test Complet',
    difficulty: 'Intermediate',
    duration: 120,
    questionsCount: 100,
    thumbnail: 'https://via.placeholder.com/400x250/EF4444/ffffff?text=Full+Test',
    isPremium: true,
  },
  {
    id: '16',
    title: 'TEF Test Complet - Niveau A2',
    description: 'Examen blanc complet pour évaluer votre niveau A2 dans toutes les compétences.',
    category: 'Test Complet',
    difficulty: 'Beginner',
    duration: 90,
    questionsCount: 75,
    thumbnail: 'https://via.placeholder.com/400x250/DC2626/ffffff?text=Test+A2',
    isPremium: true,
  },
];

export const CATEGORIES = [
  'Tous',
  'Compréhension Orale',
  'Expression Écrite',
  'Compréhension Écrite',
  'Expression Orale',
  'Vocabulaire et Grammaire',
  'Test Complet',
];
