import { Paper, Question } from '../types';

export const MOCK_QUESTIONS: { [paperId: string]: Question[] } = {
  '1': [
    {
      id: 'q1_1',
      question: 'Quelle est la capitale de la France?',
      options: ['Paris', 'Lyon', 'Marseille', 'Bordeaux'],
      correctAnswer: 0,
      explanation: 'Paris est la capitale et la plus grande ville de France.',
    },
    {
      id: 'q1_2',
      question: 'Comment dit-on "Hello" en français?',
      options: ['Au revoir', 'Bonjour', 'Merci', 'Oui'],
      correctAnswer: 1,
      explanation: '"Bonjour" signifie "Hello" ou "Good morning" en français.',
    },
    {
      id: 'q1_3',
      question: 'Quel est le verbe "être" à la première personne du singulier?',
      options: ['Je suis', 'Tu es', 'Il est', 'Nous sommes'],
      correctAnswer: 0,
      explanation: '"Je suis" est la conjugaison de "être" pour "I am".',
    },
  ],
  '2': [
    {
      id: 'q2_1',
      question: 'Quel temps verbal est utilisé pour parler d\'une action passée?',
      options: ['Présent', 'Futur', 'Passé composé', 'Conditionnel'],
      correctAnswer: 2,
      explanation: 'Le passé composé est utilisé pour décrire des actions terminées dans le passé.',
    },
  ],
};

export const MOCK_PAPERS: Paper[] = [
  {
    id: '1',
    title: 'TEF Compréhension Orale - Niveau A1',
    description: 'Test complet de compréhension orale pour débutants. Évaluez votre capacité à comprendre le français parlé dans des situations quotidiennes.',
    category: 'Compréhension Orale',
    difficulty: 'Beginner',
    duration: 30,
    questionsCount: 25,
    thumbnail: 'https://via.placeholder.com/400x250/5B21B6/ffffff?text=Oral+A1',
    isPremium: false,
  },
  {
    id: '2',
    title: 'TEF Expression Écrite - Niveau B1',
    description: 'Pratiquez votre expression écrite avec des exercices intermédiaires. Incluant des questions sur la grammaire et la composition.',
    category: 'Expression Écrite',
    difficulty: 'Intermediate',
    duration: 45,
    questionsCount: 30,
    thumbnail: 'https://via.placeholder.com/400x250/7C3AED/ffffff?text=Ecrit+B1',
    isPremium: true,
  },
  {
    id: '3',
    title: 'TEF Compréhension Écrite - Niveau B2',
    description: 'Questions de compréhension de texte de niveau avancé. Testez votre capacité à comprendre des documents complexes.',
    category: 'Compréhension Écrite',
    difficulty: 'Advanced',
    duration: 60,
    questionsCount: 40,
    thumbnail: 'https://via.placeholder.com/400x250/3B82F6/ffffff?text=Lecture+B2',
    isPremium: true,
  },
  {
    id: '4',
    title: 'TEF Vocabulaire et Grammaire - A2',
    description: 'Renforcez vos connaissances en vocabulaire et grammaire française. Parfait pour le niveau élémentaire.',
    category: 'Vocabulaire et Grammaire',
    difficulty: 'Beginner',
    duration: 40,
    questionsCount: 35,
    thumbnail: 'https://via.placeholder.com/400x250/10B981/ffffff?text=Vocab+A2',
    isPremium: false,
  },
  {
    id: '5',
    title: 'TEF Expression Orale - Niveau B2',
    description: 'Préparez-vous pour la section d\'expression orale avec des questions et situations réelles.',
    category: 'Expression Orale',
    difficulty: 'Advanced',
    duration: 35,
    questionsCount: 20,
    thumbnail: 'https://via.placeholder.com/400x250/F59E0B/ffffff?text=Oral+B2',
    isPremium: true,
  },
  {
    id: '6',
    title: 'TEF Test Complet - Niveau B1',
    description: 'Simulation complète du TEF couvrant toutes les sections. Idéal pour préparer l\'examen officiel.',
    category: 'Test Complet',
    difficulty: 'Intermediate',
    duration: 120,
    questionsCount: 100,
    thumbnail: 'https://via.placeholder.com/400x250/EF4444/ffffff?text=Full+Test',
    isPremium: true,
  },
];

export const CATEGORIES = [
  'Tous',
  'Compréhension Orale',
  'Expression Écrite',
  'Compréhension Écrite',
  'Expression Orale',
  'Vocabulaire et Grammaire',
  'Test Complet',
];
